Hello Microverse!
juandapps/hworld pull request #1
Opened 2023-03-22 22:31 UTC by juandapps

### Learning Objectives

- Create branches with different base branches.
- Understand the concept of version control.
- Follow GitHub flow.
- Open pull requests in GitHub.
- Write descriptive, easy to understand commit messages.
- Write short, detailed, easy to understand descriptions of pull requests.
- Write a descriptive and easy to understand README in business English for every project submitted.
- Demonstrate an ability to submit a project for code review.

I'm looking forward to your feedback 😁

2023-03-26 04:18 UTC, franclobo requested changes
Hi @juandapps, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/227755023-fa9d31a3-82f6-4863-8430-f469ae49d8e3.gif)

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Meaningful commits ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 04:18 UTC, franclobo commented on README.md
>    <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
- [ ] Please 🙏🏽 replace the Microverse logo with your own or remove it for professional documentation.

2023-03-26 04:18 UTC, franclobo commented on README.md
>  <!-- PROJECT DESCRIPTION -->
- [ ] Please 🙏🏽 complete all the sections in your README. All main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo for professional documentation.

| Expected | Your repo |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/227754623-dd691821-4c36-4145-935e-51895e0aee63.png) | ![image](https://user-images.githubusercontent.com/58642949/227754641-44cbdffd-c3e0-4644-a305-831a16ef0c6e.png) |

2023-03-26 05:18 UTC, franclobo requested changes
Hi @juandapps, 

# ♻️ Required Changes ♻️

![soClose](https://user-images.githubusercontent.com/58642949/227756896-58bfc90c-4f4a-4fb4-9f4a-148a8b99dc43.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️
- Correct Github flow ✔️
- Descriptive PR ✔️
- Meaningful commits ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 05:18 UTC, franclobo commented on README.md
> +  <img src="drtcode.png" alt="logo" width="140"  height="auto" />
- **[OPTIONAL]** The link of your logo is broken, please fix it for professional documentation.

2023-03-26 05:18 UTC, franclobo commented on README.md
> +<h3><b>Portfolio Project</b></h3>
- **[OPTIONAL]** Please 🙏🏽 correct the name of the project it is "Hello Microverse" instead of "Portfolio Project"

2023-03-26 05:18 UTC, franclobo commented on README.md
> +> Build a mobile-first portfolio website using flex and grid.
- [ ] Well done 👍🏽 adding al the required sections as requested in the previous review, but you have to complete it with the correct info from the current project which is "Hello Microverse"

2023-03-26 05:18 UTC, franclobo commented on README.md
> +- **Mobile First approach**
- [ ] Well done 👍🏽 adding al the required sections as requested in the previous review, but you have to complete it with the correct info from the current project which is "Hello Microverse"

2023-03-26 05:18 UTC, franclobo commented on README.md
> +- [Live Demo Link](https://dainty-gingersnap-8977c5.netlify.app/)
- [ ] Well done 👍🏽 adding al the required sections as requested in the previous review, but you have to complete it with the correct info from the current project which is "Hello Microverse".
- [ ] This milestone doesn't need to deploy, so you can omit the Live demo section or replace the link with the message "Coming soon" for professional documentation.

2023-03-26 05:18 UTC, franclobo commented on README.md
> +git clone https://github.com/juandapps/mobilefirst.git
- [ ] Well done 👍🏽 adding al the required sections as requested in the previous review, but you have to complete it with the correct info from the current project which is "Hello Microverse".
- [ ] Please 🙏🏽  correct the link of your repo for professional documentation.

2023-03-26 05:56 UTC, topeogunleye approved these changes
### Hi @juandapps, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
## [Optional] suggestions:
* [ ]  Please check my inline comments.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-26 23:11 UTC, merged

2023-03-27 15:46 UTC, levy002 reviewed
## Hello @juandapps 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Highlights
- Professional PR :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._